services:
  awesome-baby-dashboard:
    build: .
    container_name: awesome-baby-dashboard
    restart: unless-stopped
    ports:
      - "8091:3000"
    volumes:
      - ./data:/app/data
    environment:
      - APP_TITLE=ðŸ‘¶ Baby-Dashboard
      - DUE_DATE=2026-08-20T00:00:00
      - ADMIN_PIN=2026
